<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Nishant1996" ignored="4" name="Test(failed)" tests="3" failures="3" timestamp="2021-03-31T11:29:29 IST" time="0.078" errors="0">
  <testcase name="TC3" time="0.031" classname="ReRunfailedTests.sample1">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at ReRunfailedTests.sample1.TC3(sample1.java:27)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC3 -->
  <testcase name="TC8" time="0.0" classname="ReRunfailedTests.sample3">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at ReRunfailedTests.sample3.TC8(sample3.java:20)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC8 -->
  <testcase name="TC10" time="0.0" classname="ReRunfailedTests.sample3">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at ReRunfailedTests.sample3.TC10(sample3.java:33)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC10 -->
  <testcase name="TC9" time="0.0" classname="ReRunfailedTests.sample3">
    <ignored/>
  </testcase> <!-- TC9 -->
  <testcase name="TC1" time="0.0" classname="ReRunfailedTests.sample1">
    <ignored/>
  </testcase> <!-- TC1 -->
  <testcase name="TC2" time="0.0" classname="ReRunfailedTests.sample1">
    <ignored/>
  </testcase> <!-- TC2 -->
  <testcase name="TC7" time="0.0" classname="ReRunfailedTests.sample3">
    <ignored/>
  </testcase> <!-- TC7 -->
</testsuite> <!-- Test(failed) -->
